AllCops:
  TargetRubyVersion: 2.4
  Exclude:
      - 'data/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Performance/Casecmp:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: False
Style/StringLiterals:
  Enabled: false
