AllCops:
  TargetRubyVersion: 2.4
  Exclude:
      - 'data/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: False
Style/StringLiterals:
  Enabled: false

Performance/Casecmp:
  Enabled: true
