AllCops:
  TargetRubyVersion: 2.4
  Exclude:
      - 'data/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: False
Style/StringLiterals:
  Enabled: false
